spring:
  redis:
  # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
    password: 
    port: 6379
# 连接超时时间（毫秒）  
    timeout: 1000
    pool:
# 连接池配置,2.0中直接使用jedis或者lettuce配置连接池
# 最大活跃连接数，负数为不限制
      max-active: 200
# 等待可用连接的最大时间，负数为不限制
      max-wait: -1
# 最大空闲连接数
      max-idle: 8
# 最小空闲连接数
      min-idle: 0