spring:
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    bus:
      enabled: true
      trace:
        enabled: true
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8882
management:  endpoints:    web:
      exposure:
        include: bus-refresh